modLoader="javafml"
loaderVersion="[40,)"
license=" All Copyrights Belong to Robot Gentleman"

[[mods]]
modId="sixteensecondmodsp"
version="1.0"
displayName="SixteenSecondModSP"
credits="Make By HCD"
displayURL="https://github.com/KienPC1234"
logoFile="logo.png"
authors="KIENCORE DEVELOP"

[[dependencies.sixteensecondmodsp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.sixteensecondmodsp]]
    modId="kleidersplayerrenderer"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sixteensecondmodsp]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

